// src/react/index/index.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import Style from './index.css';
import fileListObj from '../../common/md/post-list';

export default class Index extends React.Component {
    render () {
        return (
            <div>
                <ul className={Style.ul}>
                    {Object.keys(fileListObj).map((name, key) => {
                        if (fileListObj[name][0] === 'post') {
                            return (<li key={key}>{key+1}. <Link to={`/${name}`}>{fileListObj[name][1]}</Link>  » <i><span>{fileListObj[name][2]}</span></i></li>);
                        }
                    })}
                </ul>
            </div>
        )
    };
};

// src/vue/index/index.vue
<template>
    <div>
        <ul>
            <li v-for="(item, name, index) in list" v-if="item[0] === 'post'">
                {{index + 1}}. <router-link
                        :to="{name: 'post', params: {name: name}}">{{item[1]}}</router-link>  » <i><span>{{item[2]}}</span></i>
            </li>
        </ul>
    </div>
</template>
<script>

    import markDownList from 'src/common/md/post-list';
    export default {
        data () {
            return {
                data: '这个是首页列表',
                list: markDownList
            }
        }
    }
</script>
<style scoped lang="scss">
    ul{
        padding: 0 20px;
    }
</style>
